AUDIO_ENABLE     = no  # Audio output on port C6
BACKLIGHT_ENABLE = no  # Enable keyboard backlight functionality
#BLUETOOTH_ENABLE = yes # Enable Bluetooth with the Adafruit EZ-Key HID
#BLUETOOTH        = RN42 # Enable Bluetooth with Rover Networks RN-42 (Sparkfun Bluesmirf) 
#VIRTSER_ENABLE   = yes # Virtual Serial
BOOTMAGIC_ENABLE = no  # Virtual DIP switch configuration(+1000)
CONSOLE_ENABLE   = no  # Console for debug(+400)
COMMAND_ENABLE   = yes # Commands for debug and configuration
EXTRAKEY_ENABLE  = yes # Audio control and System control(+450)
LEADER_ENABLE    = yes # Turn On Leader Key Support
MIDI_ENABLE      = no  # MIDI controls
MOUSEKEY_ENABLE  = yes # Mouse keys(+4700)
NKRO_ENABLE      = yes # Nkey Rollover - if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
RGBLIGHT_ENABLE  = no  # Enable WS2812 RGB underlight. 
SLEEP_LED_ENABLE = no  # Breathing sleep LED during USB suspend
TAP_DANCE_ENABLE = yes # Turn On Tap Dance
UNICODE_ENABLE   = no  # Unicode
